name: GitHubActionsDemo
on: 
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
     - name: Login
       id: login_azure
       uses: azure/login@v2
       with:
         creds: ${{ secrets.AZURE_CREDS }}

     - name: Checkout
       id: checkout
       uses: actions/checkout@v4

     - name: Deploy
       id: deploy
       uses: azure/bicep-deploy@v2
       with: 
         type: deployment
         operation: create
         name: 'bicep-deploy'
         scope: resourceGroup
         subscription-id: ${{ secrets.AZURE_SUB_ID }}
         resource-group-name: 'RG-GitHubActions-Demo'
         template-file: './bicep/storageAccount.bicep'
         parameters: '{"parStorageAccountName": "githubactionsdemohertes",
                       "parStorageSKU": "Standard_LRS"}'

