name: GitHubActionsDemo
on: 
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
     - name: Login
       id: login_azure
       uses: azure/login@v2
       with:
         creds: ${{ secrets.AZURE_CREDS }}

     - name: Checkout
       id: checkout
       uses: actions/checkout@v4
